<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <AssemblyName>DotNetTool.Builder</AssemblyName>
    <RootNamespace>DotNetTool.Builder</RootNamespace>
    <Authors>Rene Peuser</Authors>
    <Company>Rene Peuser Softwaresolutions</Company>
    <Description>This dotnet tool allows you creating your own dotnet tool based on Microsofts System.CommandLine.Experimental package.</Description>
    <Copyright>Copyright 2019 (c) Rene Peuser. All rights reserved.</Copyright>
    <PackageLicenseFile>license.txt</PackageLicenseFile>
    <PackageProjectUrl>https://renepeuser.visualstudio.com/DotNetToolBuilder</PackageProjectUrl>
    <RepositoryUrl>https://renepeuser.visualstudio.com/DotNetToolBuilder</RepositoryUrl>
    <PackageReleaseNotes>Bug-Fixes / Changes:
- Upgrade to Net5
- Fix legacy version bug and upgrade to 9.x.x, so calling dotnet tool install without version will pull the newest.
- Fix tests with cleanup.


Prerequisites
- .NET5 SDK or higher</PackageReleaseNotes>
    <PackageTags>C#;DotNet;.Net;.NetTool;.NetToolBuilder;DotNetToolBuilder;CLI;Build CLI;Build.NetTool;System.CommandLine;CommandLine;GlobalTool;LocalTool;Tool;</PackageTags>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>dotnet-newtool</ToolCommandName>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="dotnet.tool.builder.template" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="dotnet.tool.builder.template">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\license.txt" Pack="true" PackagePath="license.txt" />
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Argument.Check" Version="1.0.4" />
    <PackageReference Include="Extensions.Pack" Version="0.1.1" />
    <PackageReference Include="FileSystem.Abstraction" Version="0.1.2" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="System.CommandLine" Version="0.3.0-alpha.20054.1" />
  </ItemGroup>

</Project>
