<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>rps</ToolCommandName>
    <UserSecretsId>5c6a3829-5b41-410b-ad80-68c00c4f2e74</UserSecretsId>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Argument.Check" Version="0.9.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="3.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="3.0.0" />

    <PackageReference Include="System.CommandLine.Experimental" Version="0.3.0-alpha.19577.1" />
    <PackageReference Include="YetAnotherConsoleTables" Version="3.0.0" />

    <PackageReference Include="System.Linq.Async" Version="4.0.0-preview.8.build.9" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
